version: "3"

services:
    elgg:
        build: ./image_www
        image: seed-image-www-csrf
        container_name: elgg-10.9.0.5
        tty: true
        # ports:
        #     - "80:80"
        depends_on:
            - mysql
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.5

    mysql:
        build: ./image_mysql
        image: seed-image-mysql-csrf
        container_name: mysql-10.9.0.6
        command: --default-authentication-plugin=mysql_native_password
        tty: true
        restart: always
        cap_add:
                - SYS_NICE  # CAP_SYS_NICE (surprise an error message)
        volumes:
                - ./mysql_data:/var/lib/mysql
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.6

    attacker:
        build: ./image_attacker
        image: seed-image-attacker-csrf
        container_name: attacker-10.9.0.105
        tty: true
        # ports:
        #     - "8080:80"
        depends_on:
            - elgg
        volumes:
                - ./attacker:/var/www/attacker
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.105

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

